FROM node:18-alpine AS builder
WORKDIR /app
COPY app/frontend/package.json .
RUN npm install
COPY app/frontend/ .
RUN npm run build

FROM nginx:alpine AS final
COPY --from=builder /app/dist/so2-devops-frontend /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
